---
# Installs services required for HA proxy
- name: install http cli client
  package:
    name: httpie
    state: latest
- name: install HAProxy
  yum:
    name=haproxy state=latest
- name: enable HAProxy
  service:
    name: haproxy
    state: started
- name: configure haproxy
  template:
    src: ../templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart HAproxy

